In [17]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import stats_pkg

In [18]:
database_name = '.\\cal_prop.sqlite'
variables = ['ROLL_YEAR','ASSESSED_VALUE','ASSESSMENT_CLASS_DESCRIPTION','RE_ASSESSED_VALUE','COMM_NAME','LAND_USE_DESIGNATION','LAND_SIZE_SF','LATITUDE','LONGITUDE','POINT']
df = stats_pkg.read_database(database_name,2013,2021,variables=variables)

Reading database from .\cal_prop.sqlite
read complete

In [20]:
df = df[df['ASSESSMENT_CLASS_DESCRIPTION']=='Residential']

In [ ]:
df

In [24]:
geo_df = gpd.GeoDataFrame(df, geometry = gpd.points_from_xy(df.LONGITUDE,df.LATITUDE), crs='EPSG:4326')

Exception ignored in: <function BaseGeometry.__del__ at 0x0000023DF59C24C0>
Traceback (most recent call last):
  File "C:\Users\mmak\AppData\Local\Continuum\anaconda3\envs\geo_env\lib\site-packages\shapely\geometry\base.py", line 242, in __del__
    self.empty(val=None)
  File "C:\Users\mmak\AppData\Local\Continuum\anaconda3\envs\geo_env\lib\site-packages\shapely\geometry\base.py", line 227, in empty
    self._lgeos.GEOSGeom_destroy(self.__geom__)
KeyboardInterrupt:

In [23]:
geo_df

,ROLL_YEAR,ASSESSED_VALUE,ASSESSMENT_CLASS_DESCRIPTION,RE_ASSESSED_VALUE,COMM_NAME,LAND_USE_DESIGNATION,LAND_SIZE_SF,LATITUDE,LONGITUDE,POINT
8,2017,295000.0,Residential,295000.0,CALGARY INTERNATIONAL AIRPORT,S-FUD,190986.0,51.125707,-113.985934,POINT (-113.985933538974 51.1257068398231)
11,2017,470000.0,Residential,470000.0,SADDLE RIDGE,S-FUD,193053.0,51.131563,-113.969231,POINT (-113.969230817502 51.1315634764011)
12,2017,498500.0,Residential,398800.0,SADDLE RIDGE,S-FUD,211865.0,51.131562,-113.967841,POINT (-113.967841265385 51.131562392978)
13,2017,481000.0,Residential,384800.0,SADDLE RIDGE,S-FUD,211880.0,51.131561,-113.966387,POINT (-113.966387180366 51.1315610927284)
14,2017,450000.0,Residential,450000.0,SADDLE RIDGE,S-FUD,211720.0,51.131560,-113.964934,POINT (-113.964933682356 51.1315600110454)
...,...,...,...,...,...,...,...,...,...,...
4579986,2021,302000.0,Residential,302000.0,LIVINGSTON,None,NaN,51.188196,-114.075884,POINT (-114.075884303062 51.188196186502)
4579987,2021,235000.0,Residential,235000.0,LIVINGSTON,None,NaN,51.188196,-114.075884,POINT (-114.075884303062 51.188196186502)
4579988,2021,293500.0,Residential,293500.0,LIVINGSTON,None,NaN,51.188196,-114.075884,POINT (-114.075884303062 51.188196186502)
4579989,2021,235000.0,Residential,235000.0,LIVINGSTON,None,NaN,51.188196,-114.075884,POINT (-114.075884303062 51.188196186502)
4579990,2021,302000.0,Residential,302000.0,LIVINGSTON,None,NaN,51.188196,-114.075884,POINT (-114.075884303062 51.188196186502)